"""The generic views for the hypotheses app are generated by 6 separate urlconfs.

These are directed from experimentdb/hypothesis for example and all use generic views.

In hypothesis.py:
* hypothesis-new
* hypothesis-detail
* hypothesis-edit
* hypothesis-list
* hypothesis-delete

In manipulation.py:
* manipulation-new
* manipulation-detail
* manipulation-edit
* manipulation-list
* manipulation-delete

In process.py:
* process-new
* process-detail
* process-edit
* process-list
* process-delete

In entity.py:
* entity-new
* entity-detail
* entity-edit
* entity-list
* entity-delete

In context.py:
* context-new
* context-detail
* context-edit
* context-list
* context-delete

In evidence.py:
* evidence-new
* evidence-detail
* evidence-edit
* evidence-list
* evidence-delete

"""
