"""The cloning app contains details about how laboratory constructs are generated.

The cloning app defines the parameters for the synthesis and maintenance of constructs generated as part of an experiment.  
Constructs can be generated via either :class:`cloning.models.Cloning` or :class:`cloning.models.Mutagenesis`.


The models in this app are:

:model:`cloning.Cloning`
  This is for :class:`~reagents.models.Construct` which are cloned or subcloned from an existing library or construct, generating a new construct.
  This might involve adding a new epitope flag or generating a new deletion or insertion.
  Typically these clones are generated by PCR or restriction digestion so the details include how this occurred.
  
:model:`cloning.Mutagenesis`
  This model is for changing a :class:`reagents.models.Construct` by mutation.
  The mutation is done by either site directed mutagenesis or small deletions or insertions.
  Typically a mutagenesis involves a PCR mediated alteration in a construct sequence generating a new construct.
  The details then generally include the :class`reagents.models.Primer`  objects used for the PCR.
"""
